### ISSUE TITLE
OpenAIのRequest timed outへの対応

### ISSUE THREAD

**Issue by tamaq2048** [tamaq2048/slack-summarizer#3]
openai.error.Timeout: Request timed out

> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
>     response = conn.getresponse()
>                ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
>     httplib_response = super().getresponse()
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 1378, in getresponse
>     response.begin()
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 279, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/socket.py", line 706, in readinto
>     return self._sock.recv_into(b)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/ssl.py", line 1278, in recv_into
>     return self.read(nbytes, buffer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/ssl.py", line 1134, in read
>     return self._sslobj.read(len, buffer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TimeoutError: The read operation timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
>     raise reraise(type(error), error, _stacktrace)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
>     raise value
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 538, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
>     raise ReadTimeoutError(
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 516, in request_raw
>     result = _thread_context.session.request(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/adapters.py", line 532, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 207, in <module>
>     runner()
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 194, in runner
>     text = summarize("\n".join(spilitted_messages), LANGUAGE)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 33, in summarize
>     response = openai.ChatCompletion.create(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line [15](https://github.com/tamaq2048/slack-summarizer/actions/runs/5563986349/job/15069868415#step:5:16)3, in create
>     response, _, api_key = requestor.request(
>                            ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 2[16](https://github.com/tamaq2048/slack-summarizer/actions/runs/5563986349/job/15069868415#step:5:17), in request
>     result = self.request_raw(
>              ^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 5[26](https://github.com/tamaq2048/slack-summarizer/actions/runs/5563986349/job/15069868415#step:5:27), in request_raw
>     raise error.Timeout("Request timed out: {}".format(e)) from e
> openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=4[43](https://github.com/tamaq2048/slack-summarizer/actions/runs/5563986349/job/15069868415#step:5:44)): Read timed out. (read timeout=[60](https://github.com/tamaq2048/slack-summarizer/actions/runs/5563986349/job/15069868415#step:5:61)0)
> Error: Process completed with exit code 1.

**Comment by tamaq2048** [comment]
エラーハンドリングとユーザへの通知のみを実装
エラーが発生した際のトークン数を通知に含めることができないか検討

**Comment by tamaq2048** [comment]
指数バックオフ戦略を採用したリトライロジックを実装
