### ISSUE TITLE
OpenAIのRateLimitErrorへの対応

### ISSUE THREAD

**Issue by tamaq2048** [tamaq2048/slack-summarizer#4]
openai.error.RateLimitError

> Traceback (most recent call last):
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 207, in <module>
>     runner()
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 194, in runner
>     text = summarize("\n".join(spilitted_messages), LANGUAGE)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 33, in summarize
>     response = openai.ChatCompletion.create(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line [15](https://github.com/tamaq2048/slack-summarizer/actions/runs/5547450782/job/15026629718#step:5:16)3, in create
>     response, _, api_key = requestor.request(
>                            ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
>     resp, got_stream = self._interpret_response(result, stream)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 6[19](https://github.com/tamaq2048/slack-summarizer/actions/runs/5547450782/job/15026629718#step:5:20), in _interpret_response
>     self._interpret_response_line(
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
>     raise self.handle_error_response(
> openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-vdJvLafeqZfcjpGf2zDr3zTM on requests per min. Limit: 3 / min. Please try again in [20](https://github.com/tamaq2048/slack-summarizer/actions/runs/5547450782/job/15026629718#step:5:21)s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
> Error: Process completed with exit code 1.

**Comment by tamaq2048** [comment]
以下の戦略を採用
- リクエストの頻度の制限
- 指数バックオフ戦略を採用したリトライロジック
