### ISSUE TITLE
OpenAIのError communicating with OpenAIへの対応

### ISSUE THREAD

**Issue by tamaq2048** [tamaq2048/slack-summarizer#5]
openai.error.APIConnectionError: Error communicating with OpenAI

> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
>     response = conn.getresponse()
>                ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
>     httplib_response = super().getresponse()
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 1378, in getresponse
>     response.begin()
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 287, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
>     raise reraise(type(error), error, _stacktrace)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
>     response = conn.getresponse()
>                ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
>     httplib_response = super().getresponse()
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 1378, in getresponse
>     response.begin()
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py", line 287, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 516, in request_raw
>     result = _thread_context.session.request(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 207, in <module>
>     runner()
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 194, in runner
>     text = summarize("\n".join(spilitted_messages), LANGUAGE)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/runner/work/slack-summarizer/slack-summarizer/summarizer.py", line 33, in summarize
>     response = openai.ChatCompletion.create(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line [15](https://github.com/tamaq2048/slack-summarizer/actions/runs/5512530729/job/14923991347#step:5:16)3, in create
>     response, _, api_key = requestor.request(
>                            ^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 2[16](https://github.com/tamaq2048/slack-summarizer/actions/runs/5512530729/job/14923991347#step:5:17), in request
>     result = self.request_raw(
>              ^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/api_requestor.py", line 5[28](https://github.com/tamaq2048/slack-summarizer/actions/runs/5512530729/job/14923991347#step:5:29), in request_raw
>     raise error.APIConnectionError(
> openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> Error: Process completed with exit code 1.

**Comment by tamaq2048** [comment]
指数バックオフによるリトライを実装
